### ISSUE TITLE
Can Duplicate Tabs Closer work without Containers?

### ISSUE THREAD

**Issue by strangeh** [Peuj/duplicate-tabs-closer#27]
I don't use containers but they are required to be turned on...
And it’s annoying because containers add extra items to the interface which i don't needed.

So... can you add some possibility to not use containers in your such a great extension?

Also, maybe you can give us some quick-fix instructions, with the help of which we can turn off this requirement without waiting for the next version of the extension?

**Comment by Peuj** [comment]
Duplicate Tabs Closer doesn't need containers. I never use containers myself. :)
Can you describe your problem, so I can reproduce it on my side?

**Comment by strangeh** [comment]
Firefox 70.0.1, i just install DTS 3.4.1 and no matter what settings i change - i see this:
[https://i.imgur.com/0Qck619.png](url)

I tried to create a new profile in the browser, i tried to disable all other extensions - nothing helps...

**Comment by Peuj** [comment]
OK I understand your problem.

Duplicate Tabs Closer doesn't `requires Container Tabs` if containers exist it simply use the container API to get information. It doesn't need containers or create container.

Firefox enables automatically the `Enable Container Tabs` if an extension is using container API.
So there is nothing I can do to prevent this.

The scope with containers is visible because the feature is available on Firefox. If you don't use container then don't use this scope. This has no impact on containers.

**Comment by strangeh** [comment]
Was a bit confused by this "if":
> ...if containers exist DTC simply use the container API to get information...

Because there is no "if"...
It seems DTC use container API regardless of whether containers are on or off, whether they exist or not.

And you say that nothing you can do to stop extension from using container API, right?
Sad if so : (

**Comment by jesus2099** [comment]
I have a problem here on Linux Firefox 91.

I had to deactivate the useful Duplicate Tabs extension because it makes Send to Containers appear in the right-click contextual menu of each href links.

By doing this, it prevents me from quickly copying HREF URL (right-click, C) because it has the same shortcut (C).

Still sure there is no way to NOT use containers?
