### ISSUE TITLE
Older Tab - Newer Tab (Question)

### ISSUE THREAD

**Issue by smaragdus** [Peuj/duplicate-tabs-closer#30]
Hello,

This is by far the most cuztomizable duplicate tabs killer I have ever found and it is open source to boot, excellent work, thanks!

I have a question- what defines which tab is considered older and which- newer? The time a tab was opened? Last time it was active? The position of the tab in the tab bar? I find this ambiguous.

Example- in options I have set:

```
Priority
Keep older tab
```
but it does not work as I expect it to work. Suppose that I have 10 open tabs and 2 duplicates- one at position 1 and one at position 10. The one at position 1 is older, it has been opened first so I expect this duplicate tab at position 1 to be kept open. But in fact [Duplicate Tabs Closer](https://github.com/Peuj/duplicate-tabs-closer) closes it and keeps the duplicate at position 10.

I would prefer the criterion for newer/older tabs to be their position- if there are two duplicate tabs- one at position 5 and another at position 15, the one kept should be that at position 5 (opened earlier, it appears first in the tab bar). the one closed should be that at position 15 (opened later, it appears second in the tab bar).

Am I missing something?

Regards

**Comment by Peuj** [comment]
Hi,

The tab age is defined by its `id` not its `index`.
The `index` only indicates the position of the tab and as the tab can be moved it's not a good indicator of its age.
The `id` is a better indicator as the `id` is increased each time there is a new tab. So by default the tab with the lower id is the older.
Of course this rule is not perfect because if you open a new link in an existing tab the id is then not relevant.
I'm currently rewriting the code and I'll use the last load date.

**Comment by smaragdus** [comment]
@Peuj 

Thank you for the quick  and detailed response and clarification.

I had the impression that somehow sometimes Duplicate Tabs Closer was closing the older tab in stead of the newer tab. I don't know whether someone else has experienced such behaviour.

If it happens that I encounter a problem or I can think of an improvement I will post here at issues page.

Since this was not a real issue but just a question and since I am satisfied with your answer feel free to close this issue. I am not doing it myself because you may have some reasons to keep it open.
